version: '3.8'

services:
  ebay-automation:
    build: .
    container_name: ebay-automation
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      # Persist database
      - ./data:/data
      # Persist logs
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=America/New_York  # Adjust to your timezone
    user: "1000:1000" # Run as natewier user (UID 1000)
    networks:
      - ebay-net
    # Resource limits for RPi
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  ebay-net:
    driver: bridge


